/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData i049_breakfast = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData i050_french_fries = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData i001_popcorn = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData i002_tea = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData i003_chinese_food = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData i004_tomato_sauce = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData i005_cola_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData i006_burger_2 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData i007_burger_1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData i008_fried_potatoes = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData i009_coffee = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData i010_burger = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData i011_ice_cream_1 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData i012_cola = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData i013_milkshake = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData i014_sauces = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData i015_hot_dog_1 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData i016_chicken_leg_1 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData i017_croissant = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData i018_cheese = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData i019_sausage = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData i020_fried_egg = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData i021_fried_chicken = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData i022_serving_dish = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData i023_pizza_slice = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData i024_chef_hat = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData i025_meat = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData i026_ice_cream = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData i027_donut = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData i028_rice = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData i029_package = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData i030_kebab = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData i031_delivery = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData i032_food_truck = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData i033_waiter_1 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData i034_waiter = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData i035_taco = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData i036_chips = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData i037_soda = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData i038_take_away = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData i039_fork = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData i040_coffee_cup = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData i041_waffle = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData i042_beer = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData i043_chicken_leg = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData i044_pitcher = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData i045_coffee_machine = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData i046_noodles = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData i047_menu = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData i048_hot_dog = const IconData(0xe831, fontFamily: _kFontFam);
}
